USE ucubot;
CREATE TABLE student(
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL, 
    user_id VARCHAR(50) NOT NULL,
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY);
